ДЗ 1
Olegiwe/2020-1-Atom-QA-Python-O-Kuznetsov pull request #1
Opened 2020-03-04 21:33 UTC by Olegiwe

# Домашнее задание № 1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
* Реализованы тесты для int, str, dict, set и list
* Настроено окружение
*

2020-03-12 13:35 UTC, sniiick requested changes
Много лишних параметризаций в тестах. Надо сократить и оставить только те, которые действительно нужны

2020-03-12 13:35 UTC, snicks92 commented on pipenv_test/tests/test_dict.py
> +        if i not in dict1:
Получается, что половина параметров бесполезны так как ничего не проверяют.

2020-03-12 13:35 UTC, snicks92 commented on pipenv_test/tests/test_list.py
> +    @pytest.mark.parametrize('rnd', random.sample(range(100), 20))
20 абсолютно одинаковых параметров с точки зрения проверки на индексы в тесте. хватит и 3х конкретных

2020-03-12 13:35 UTC, snicks92 commented on pipenv_test/tests/test_set.py
> +    @pytest.mark.parametrize('lst', [[random.randint(0, 3) for _ in range(1000)] for _ in range(20)])
Какие то очень страшные цифры, 20 списков по 1000 в каждом. Давай сократим, кажется что между ними никакой разницы

2020-03-12 13:35 UTC, snicks92 commented on pipenv_test/tests/test_str.py
> +        assert str0 == str1 and str0 == str2 and str0 == str3
str0 == str1 == str2 == str3
Но вообще как раз таки вот тут лучше сделать параметризацию. В отличие от теста выше где опять же между параметрами нет никакой разницы

2020-03-15 21:56 UTC, Olegiwe commented
Я немного переработал тесты, переделал параметризации там, где было указано, а ещё чуть-чуть переделал код для того, чтобы pylint ругался чуть меньше.

2020-03-20 20:26 UTC, sniiick requested changes
С тестом test_dict_key_error снова вопросы. Остальное ок.

2020-03-20 20:26 UTC, snicks92 commented on pipenv_test/tests/test_dict.py
> +        if i not in dict1:
А что поменялось? Зачем такое количество параметров, если возьмешь ты только те что есть в [1, 3, 5, 7, 9].
Если пишешь тест на то что ключа нет в словаре, то сгенерируй все значения которых нет и проверь их. Опять же стоит учесть какие именно значения стоит проверить.

2020-03-26 15:42 UTC, Olegiwe commented on pipenv_test/tests/test_dict.py
> +        if i not in dict1:
Придал параметрам чуть более осмысленный вид.

2020-03-27 13:38 UTC, sniiick approved these changes

2020-03-27 13:39 UTC, merged